# Site wide configuration

title:    KrishnaKanth Nakka        
locale:           en_US
url: https://krishnakanthnakka.github.io
# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: rouge
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner: 
  name: Krishna Kanth Nakka
  avatar: bio2.jpg
  position: Doctoral Student 
  school: CVLab, EPFL
  place: Lausanne, Switzerland
  bio: 
  email: krishna.nakka@epfl.ch
  disqus-shortname: KK
  twitter: 
  facebook: 
  google:
    plus: 
    analytics: UA-125946091-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: 
  stackoverflow: 
  linkedin: krishna-kanth-nakka-b73a4b44/
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  codepen: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
